language: php

notifications:
  email: false

php:
  - 7.0

install:
  - composer install

script:
  - composer create
  - composer generate
  - phpunit --testsuite Unit -- --coverage-clover=coverage.clover