language: php

notifications:
  email: false

php:
  - 7.0

install:
  - composer install

script:
  - composer create
  - composer generate
  - composer test -- --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover